version: "3"
services:
    agrosavia-mysql:
        image: mysql:8.0
        container_name: agrosavia-mysql
        cap_add:
          - SYS_NICE  # CAP_SYS_NICE
        ports:
          - "3005:3306"
        networks: 
            - network_agrosavia
        volumes:
          - ./run/var:/var/lib/mysql
        environment:
          # Usar random por defecto para prd
          - MYSQL_ROOT_PASSWORD=securerootpassword 
          - MYSQL_DATABASE=${DB_DATABASE}
          - MYSQL_USER=${DB_USERNAME}
          - MYSQL_PASSWORD=${DB_PASSWORD}
          
    agrosavia-laravel:
        build: ./back-end
        container_name: agrosavia-laravel
        ports:
          - "9005:80"
        volumes:
          - ./back-end:/var/www/html/
          - ./vhost.conf:/etc/apache2/sites-available/000-default.conf
        depends_on:
          - agrosavia-mysql
        links:
          - agrosavia-mysql
        networks: 
          - network_agrosavia
        
        command: >
                bash -c "cd /var/www/html/ 
                && composer update 
                && composer install
                && php artisan storage:link   
                && composer update 
                && composer install
                && php artisan migrate:fresh --seed
                && apache2-foreground"
        
    agrosavia-ng:
        container_name: agrosavia-ng
        #restart: always
        build: 
            context: ./front-end
            dockerfile: Dockerfile
        depends_on:
          - agrosavia-laravel
        ports:
            - "4005:80"
        #entrypoint: node
        networks: 
            - network_agrosavia
        volumes:
            - ./front-end:/usr/src/app/
            - ./front-end/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./front-end/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./front-end/nginx/blockips.conf:/etc/nginx/blockips.conf
networks: 
  network_agrosavia:
    driver: bridge

                # && composer update 
                # && composer install
                # && php artisan migrate:fresh --seed